apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  labels:
    k8s-k8s-app: echoserver
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: echoserver
  template:
    metadata:
      labels:
        k8s-app: echoserver
    spec:
      containers:
      - name: echoserver
        image: registry.cn-hangzhou.aliyuncs.com/google-containers/echoserver:1.4
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  labels:
    k8s-app: echoserver
spec:
  type: NodePort
  selector:
    k8s-app: echoserver
  ports:
  - name: http
    port: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-echoserver
spec:
  tls:
  - hosts:
    - echoserver.minikube.local
    secretName: minikube-tls-certificate
  rules:
  - host: echoserver.minikube.local
    http:
      paths:
      - backend:
          serviceName: echoserver
          servicePort: 8080